import { TravelPackage, Trip, Booking, Quote, SearchIntent } from '../types';

// Mock search intents
export const mockSearches: SearchIntent[] = [
  {
    id: 'search-1',
    destination: 'Goa',
    dates: {
      checkIn: '2026-12-15',
      checkOut: '2026-12-20',
      flexible: true,
    },
    passengers: {
      adults: 2,
      children: 1,
      infants: 0,
    },
    budget: {
      amount: 60000,
      currency: 'INR',
    },
    preferences: {
      vibe: ['beach', 'relaxed'],
      hotelCategory: '4-star',
      flightClass: 'economy',
    },
    rawQuery: 'Goa, 5 nights, 2 adults + 1 child, budget ₹60k, beach, mid-Dec, flexible dates',
    createdAt: '2026-02-06T10:30:00Z',
  },
];

// Mock packages
export const mockPackages: TravelPackage[] = [
  {
    id: 'pkg-1',
    searchId: 'search-1',
    name: 'Beach Paradise - Calangute',
    outboundFlight: {
      id: 'flight-out-1',
      airline: 'IndiGo',
      flightNumber: '6E 345',
      departure: {
        airport: 'DEL',
        city: 'Delhi',
        time: '09:30',
        date: '2026-12-15',
      },
      arrival: {
        airport: 'GOI',
        city: 'Goa',
        time: '12:15',
        date: '2026-12-15',
      },
      duration: '2h 45m',
      stops: 0,
      cabinClass: 'Economy',
      price: 8500,
    },
    returnFlight: {
      id: 'flight-ret-1',
      airline: 'IndiGo',
      flightNumber: '6E 346',
      departure: {
        airport: 'GOI',
        city: 'Goa',
        time: '18:30',
        date: '2026-12-20',
      },
      arrival: {
        airport: 'DEL',
        city: 'Delhi',
        time: '21:00',
        date: '2026-12-20',
      },
      duration: '2h 30m',
      stops: 0,
      cabinClass: 'Economy',
      price: 9200,
    },
    hotel: {
      id: 'hotel-1',
      name: 'Taj Holiday Village Resort & Spa',
      category: '5-star',
      rating: 4.5,
      location: 'Calangute',
      area: 'North Goa',
      amenities: ['Pool', 'Beach Access', 'Spa', 'Restaurant', 'Gym'],
      roomType: 'Deluxe Room',
      mealPlan: 'Breakfast included',
      nights: 5,
      pricePerNight: 6500,
      totalPrice: 32500,
      images: ['goa-beach-resort'],
    },
    transfers: [
      {
        id: 'transfer-1',
        type: 'airport-hotel',
        vehicle: 'Sedan',
        from: 'Goa Airport',
        to: 'Taj Holiday Village',
        price: 800,
      },
      {
        id: 'transfer-2',
        type: 'hotel-airport',
        vehicle: 'Sedan',
        from: 'Taj Holiday Village',
        to: 'Goa Airport',
        price: 800,
      },
    ],
    activities: [
      {
        id: 'activity-1',
        name: 'Dudhsagar Falls Day Trip',
        description: 'Full-day excursion to majestic Dudhsagar waterfalls with lunch',
        duration: '8 hours',
        price: 2500,
        category: 'Adventure',
      },
      {
        id: 'activity-2',
        name: 'Sunset Cruise on Mandovi River',
        description: 'Evening cruise with live music and dinner',
        duration: '3 hours',
        price: 1800,
        category: 'Leisure',
      },
    ],
    totalPrice: 56100,
    priceBreakdown: {
      flights: 17700,
      hotel: 32500,
      transfers: 1600,
      activities: 4300,
    },
    confidenceScore: 92,
    reasoning: [
      'Perfect beach location in Calangute',
      'Premium 5-star resort within budget',
      'Direct flights minimize travel time',
      'Includes signature Goa experiences',
    ],
    status: 'available',
  },
  {
    id: 'pkg-2',
    searchId: 'search-1',
    name: 'Budget Beach Escape - Candolim',
    outboundFlight: {
      id: 'flight-out-2',
      airline: 'SpiceJet',
      flightNumber: 'SG 917',
      departure: {
        airport: 'DEL',
        city: 'Delhi',
        time: '06:00',
        date: '2026-12-15',
      },
      arrival: {
        airport: 'GOI',
        city: 'Goa',
        time: '08:45',
        date: '2026-12-15',
      },
      duration: '2h 45m',
      stops: 0,
      cabinClass: 'Economy',
      price: 6800,
    },
    returnFlight: {
      id: 'flight-ret-2',
      airline: 'SpiceJet',
      flightNumber: 'SG 918',
      departure: {
        airport: 'GOI',
        city: 'Goa',
        time: '20:15',
        date: '2026-12-20',
      },
      arrival: {
        airport: 'DEL',
        city: 'Delhi',
        time: '22:45',
        date: '2026-12-20',
      },
      duration: '2h 30m',
      stops: 0,
      cabinClass: 'Economy',
      price: 7100,
    },
    hotel: {
      id: 'hotel-2',
      name: 'Lemon Tree Amarante Beach Resort',
      category: '4-star',
      rating: 4.2,
      location: 'Candolim',
      area: 'North Goa',
      amenities: ['Pool', 'Beach Access', 'Restaurant', 'Gym'],
      roomType: 'Superior Room',
      mealPlan: 'Breakfast included',
      nights: 5,
      pricePerNight: 4800,
      totalPrice: 24000,
      images: ['goa-beach-hotel'],
    },
    transfers: [
      {
        id: 'transfer-3',
        type: 'airport-hotel',
        vehicle: 'Sedan',
        from: 'Goa Airport',
        to: 'Lemon Tree Amarante',
        price: 750,
      },
      {
        id: 'transfer-4',
        type: 'hotel-airport',
        vehicle: 'Sedan',
        from: 'Lemon Tree Amarante',
        to: 'Goa Airport',
        price: 750,
      },
    ],
    activities: [
      {
        id: 'activity-3',
        name: 'North Goa Beach Hopping',
        description: 'Explore Calangute, Baga, and Anjuna beaches',
        duration: '6 hours',
        price: 1500,
        category: 'Sightseeing',
      },
    ],
    totalPrice: 41400,
    priceBreakdown: {
      flights: 13900,
      hotel: 24000,
      transfers: 1500,
      activities: 1500,
    },
    confidenceScore: 88,
    reasoning: [
      'Best value for budget constraint',
      'Quality 4-star resort with beach access',
      'Early morning flight maximizes vacation time',
      'Leaves room for additional spending',
    ],
    status: 'available',
  },
  {
    id: 'pkg-3',
    searchId: 'search-1',
    name: 'Luxury Family Retreat - Panjim',
    outboundFlight: {
      id: 'flight-out-3',
      airline: 'Air India',
      flightNumber: 'AI 864',
      departure: {
        airport: 'DEL',
        city: 'Delhi',
        time: '11:15',
        date: '2026-12-15',
      },
      arrival: {
        airport: 'GOI',
        city: 'Goa',
        time: '14:00',
        date: '2026-12-15',
      },
      duration: '2h 45m',
      stops: 0,
      cabinClass: 'Economy',
      price: 9200,
    },
    returnFlight: {
      id: 'flight-ret-3',
      airline: 'Air India',
      flightNumber: 'AI 865',
      departure: {
        airport: 'GOI',
        city: 'Goa',
        time: '15:30',
        date: '2026-12-20',
      },
      arrival: {
        airport: 'DEL',
        city: 'Delhi',
        time: '18:00',
        date: '2026-12-20',
      },
      duration: '2h 30m',
      stops: 0,
      cabinClass: 'Economy',
      price: 9800,
    },
    hotel: {
      id: 'hotel-3',
      name: 'Grand Hyatt Goa',
      category: '5-star',
      rating: 4.7,
      location: 'Bambolim',
      area: 'Central Goa',
      amenities: ['Pool', 'Kids Club', 'Spa', 'Multiple Restaurants', 'Casino', 'Gym'],
      roomType: 'Family Suite',
      mealPlan: 'Breakfast & Dinner',
      nights: 5,
      pricePerNight: 8500,
      totalPrice: 42500,
      images: ['goa-luxury-resort'],
    },
    transfers: [
      {
        id: 'transfer-5',
        type: 'airport-hotel',
        vehicle: 'SUV',
        from: 'Goa Airport',
        to: 'Grand Hyatt',
        price: 1200,
      },
      {
        id: 'transfer-6',
        type: 'hotel-airport',
        vehicle: 'SUV',
        from: 'Grand Hyatt',
        to: 'Goa Airport',
        price: 1200,
      },
    ],
    activities: [
      {
        id: 'activity-4',
        name: 'Dolphin Watching & Island Tour',
        description: 'Boat trip to spot dolphins and visit Grand Island',
        duration: '4 hours',
        price: 3000,
        category: 'Wildlife',
      },
      {
        id: 'activity-5',
        name: 'Spice Plantation Tour',
        description: 'Guided tour with traditional lunch',
        duration: '5 hours',
        price: 2000,
        category: 'Cultural',
      },
    ],
    totalPrice: 68900,
    priceBreakdown: {
      flights: 19000,
      hotel: 42500,
      transfers: 2400,
      activities: 5000,
    },
    confidenceScore: 85,
    reasoning: [
      'Premium family-friendly resort',
      'Half-board meal plan included',
      'Spacious suite accommodations',
      'Slightly over budget but exceptional value',
    ],
    status: 'available',
  },
];

// Mock trips
export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    booking: {
      id: 'booking-1',
      quoteId: 'quote-1',
      packageId: 'pkg-1',
      status: 'ticketed',
      travelers: [
        {
          id: 'traveler-1',
          firstName: 'Rajesh',
          lastName: 'Kumar',
          type: 'adult',
          dateOfBirth: '1985-03-15',
          passport: {
            number: 'M1234567',
            expiry: '2030-05-20',
            nationality: 'Indian',
          },
        },
        {
          id: 'traveler-2',
          firstName: 'Priya',
          lastName: 'Kumar',
          type: 'adult',
          dateOfBirth: '1988-07-22',
          passport: {
            number: 'M2345678',
            expiry: '2029-08-15',
            nationality: 'Indian',
          },
        },
        {
          id: 'traveler-3',
          firstName: 'Aarav',
          lastName: 'Kumar',
          type: 'child',
          dateOfBirth: '2016-11-10',
        },
      ],
      pnr: 'TBO8923X',
      documents: [
        {
          id: 'doc-1',
          type: 'e-ticket',
          name: 'Flight E-Ticket - 6E 345/346',
          url: '#',
          createdAt: '2026-02-05T14:30:00Z',
        },
        {
          id: 'doc-2',
          type: 'hotel-voucher',
          name: 'Hotel Voucher - Taj Holiday Village',
          url: '#',
          createdAt: '2026-02-05T14:32:00Z',
        },
        {
          id: 'doc-3',
          type: 'transfer-voucher',
          name: 'Transfer Voucher - Airport Transfers',
          url: '#',
          createdAt: '2026-02-05T14:33:00Z',
        },
      ],
      createdAt: '2026-02-05T14:30:00Z',
      tripStart: '2026-12-15',
      tripEnd: '2026-12-20',
    },
    package: mockPackages[0],
    timeline: [
      {
        id: 'event-1',
        type: 'flight',
        title: 'Departure - IndiGo 6E 345',
        description: 'Delhi (DEL) → Goa (GOI)',
        datetime: '2026-12-15T09:30:00',
        status: 'pending',
      },
      {
        id: 'event-2',
        type: 'transfer',
        title: 'Airport Transfer',
        description: 'Goa Airport → Taj Holiday Village',
        datetime: '2026-12-15T12:30:00',
        status: 'pending',
      },
      {
        id: 'event-3',
        type: 'hotel',
        title: 'Hotel Check-in',
        description: 'Taj Holiday Village Resort & Spa',
        datetime: '2026-12-15T14:00:00',
        status: 'pending',
      },
      {
        id: 'event-4',
        type: 'activity',
        title: 'Dudhsagar Falls Day Trip',
        description: 'Full-day excursion with lunch',
        datetime: '2026-12-17T08:00:00',
        status: 'pending',
      },
      {
        id: 'event-5',
        type: 'activity',
        title: 'Sunset Cruise on Mandovi River',
        description: 'Evening cruise with dinner',
        datetime: '2026-12-18T17:00:00',
        status: 'pending',
      },
      {
        id: 'event-6',
        type: 'hotel',
        title: 'Hotel Check-out',
        description: 'Taj Holiday Village Resort & Spa',
        datetime: '2026-12-20T11:00:00',
        status: 'pending',
      },
      {
        id: 'event-7',
        type: 'transfer',
        title: 'Airport Transfer',
        description: 'Taj Holiday Village → Goa Airport',
        datetime: '2026-12-20T16:00:00',
        status: 'pending',
      },
      {
        id: 'event-8',
        type: 'flight',
        title: 'Return - IndiGo 6E 346',
        description: 'Goa (GOI) → Delhi (DEL)',
        datetime: '2026-12-20T18:30:00',
        status: 'pending',
      },
    ],
    alerts: [],
    status: 'upcoming',
  },
];

export const mockQuotes: Quote[] = [
  {
    id: 'quote-1',
    packageId: 'pkg-1',
    agentId: 'agent-1',
    clientName: 'Rajesh Kumar',
    clientEmail: 'rajesh.kumar@example.com',
    markup: 5000,
    finalPrice: 61100,
    validUntil: '2026-02-13T23:59:59Z',
    status: 'approved',
    notes: 'Client requested extra activity options',
    createdAt: '2026-02-05T11:00:00Z',
  },
];
